### PR TITLE
fix: step template issues

### LINKED ISSUE #826: Can't set StepTemplate.Packages.Properties.Extract
**Describe the bug**
When setting the Step Template [extract](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/step_template#extract-1) value I get the error

```
Attribute packages[0].properties.extract Extract must be True or False, got: False
```

**Template**
```
resource "octopusdeploy_step_template" "fake-install" {
  space_id        = octopusdeploy_space.auto-insurance.id
  action_type     = "Octopus.RunScript"
  name            = "Fake Install"
  step_package_id = ""

  parameters = [
    {
      id = "0b22233d-dc63-4c45-8e59-adb176d2fb1b"
      name = "Package"
      
      display_settings = {
        "Octopus.ControlType" : "Package"
      }
    }
  ]

  packages = [
    {
      feed_id = data.octopusdeploy_feeds.builtin.id
      name = "Package"
      
      properties = {
        extract = "False"
        selection_mode : "deferred"
        package_parameter_name : "Package"
      }
    }
  ]

  properties = {
    "Octopus.Action.Script.ScriptSource" : "Inline",
    "Octopus.Action.Script.Syntax" : "PowerShell",
    "Octopus.Action.Script.ScriptBody" : "echo \"Done\""
  }
}
```

### LINKED ISSUE #827: Error if the StepTemplate Parameter Label is not specified
**Describe the bug**
Using the `octopusdeploy_step_template` but not specifing the `label` attribute for a parameter results in the error:

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to octopusdeploy_step_template.fake-install, provider "provider[\"registry.terraform.io/octopusdeploylabs/octopusdeploy\"]"     
│ produced an unexpected new value: .parameters[0].label: was null, but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

**Steps to reproduce**
```

resource "octopusdeploy_step_template" "fake-install" {
  space_id        = octopusdeploy_space.auto-insurance.id
  action_type     = "Octopus.RunScript"
  name            = "Fake Install"
  step_package_id = ""

  parameters = [
    {
      id = "0b22233d-dc63-4c45-8e59-adb176d2fb1b"
      name = "Package"
      
      display_settings = {
        "Octopus.ControlType" : "Package"
      }
    }
  ]

  packages = [
    {
      feed_id = data.octopusdeploy_feeds.builtin.feeds[0].id
      name = "Package"
      
      properties = {
        selection_mode : "deferred"
        package_parameter_name : "Package"
      }
    }
  ]

  properties = {
    "Octopus.Action.Script.ScriptSource" : "Inline",
    "Octopus.Action.Script.Syntax" : "PowerShell",
    "Octopus.Action.Script.ScriptBody" : "echo \"Done\""
  }
}
```

### LINKED ISSUE #829: StepTemplate Package Properties are not converted from snake_case to Pascal Case
**Describe the bug**
When a step template with packages is created, the package property collection contains properties that are not cased correctly. The validation forces me into snake case.

Via terraform the packages collection looks like:
```
 "Packages": [
    {
      "Id": "922cd70a-509c-43c6-b89e-6859ed99a8a8",
      "Name": "Package",
      "PackageId": null,
      "FeedId": "Feeds-1003",
      "AcquisitionLocation": "Server",
      "Properties": {
        "extract": "True",
        "package_parameter_name": "Package",
        "purpose": "",
        "selection_mode": "deferred"
      }
    }
  ],
```

Whereas when edited via the WebUI, it looks like:
```
  "Packages": [
    {
      "Id": "922cd70a-509c-43c6-b89e-6859ed99a8a8",
      "Name": "Package",
      "PackageId": null,
      "FeedId": "Feeds-1003",
      "AcquisitionLocation": "Server",
      "Properties": {
        "SelectionMode": "deferred",
        "PackageParameterName": "Package",
        "Purpose": ""
      }
    }
  ],
```

This means that when the template is consumed the package properties are not read correctly.

Full terraform:
```

resource "octopusdeploy_step_template" "fake-install" {
  space_id        = octopusdeploy_space.auto-insurance.id
  action_type     = "Octopus.Script"
  name            = "Fake Install"
  step_package_id = ""

  parameters = [
    {
      id = "0b22233d-dc63-4c45-8e59-adb176d2fb1b"
      name = "Package"
      label = ""

      display_settings = {
        "Octopus.ControlType" : "Package"
      }
    }
  ]

  packages = [
    {
      feed_id = data.octopusdeploy_feeds.builtin.feeds[0].id
      name = "Package"

      properties = {
        selection_mode : "deferred"
        package_parameter_name : "Package"
      }
    }
  ]

  properties = {
    "Octopus.Action.Script.ScriptSource" : "Inline",
    "Octopus.Action.Script.Syntax" : "PowerShell",
    "Octopus.Action.Script.ScriptBody" : "echo \"Done\""
  }
}


```

### PR DESCRIPTION
**Pull request by domenicsim1**
closes #827
closes #826
closes #829

### CODE REVIEW

File: octopusdeploy_framework/schemas/step_template.go [hunk 1]
```diff
@@ -163,6 +163,7 @@ func GetStepTemplateParameterResourceSchema() rs.ListNestedAttribute {
 				"label": rs.StringAttribute{
 					Description: "The label shown beside the parameter when presented in the deployment process. Example: `Server name`.",
 					Optional:    true,
+					Computed:    true,
```
Comment (droyad) [inline octopusdeploy_framework/schemas/step_template.go:166]: Does this mean the user _can_ set it?

**Review by droyad — APPROVED** [review]

File: octopusdeploy_framework/schemas/step_template.go (hunk 1 above)
Comment (domenicsim1) [reply octopusdeploy_framework/schemas/step_template.go:166]: yes , should they not be able to?
