### PR TITLE
fix: panic using project_verisoning_strategy without donorpackage

### LINKED ISSUE #855: Provider crash when creating a `octopusdeploy_project_versioning_strategy` resource
**Describe the bug**
Provider crashes when trying to add a 'octopusdeploy_project_versioning_strategy'. Also unable to import it.

**Steps to reproduce**
Create a project, then add a 'octopusdeploy_project_versioning_strategy' resource.

**Expected behavior**
Being able to specify via terraform the versioning strategy. I'd be ok with importing the current value but it doesn't look like it's supported.

**Logs and other supporting information**

```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-octopusdeploy_v0.39.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x10c33c5]

goroutine 47 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy_framework.mapProjectVersioningStrategyToState(...)
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy_framework/resource_project_versioning_strategy.go:188
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy_framework.(*projectVersioningStrategyResource).Create(0xc00052e040, {0x17782f8, 0xc0008907e0}, {{{{0x1780058, 0xc0008915c0}, {0x1431260, 0xc000891320}}, {0x1784490, 0xc0005370e0}}, {{{0x1780058, ...}, ...}, ...}, ...}, ...)
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy_framework/resource_project_versioning_strategy.go:80 +0x705
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc00073c000, {0x17782f8, 0xc0008907e0}, 0xc00094f540, 0xc00094f518)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_createresource.go:101 +0x578
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc00073c000, {0x17782f8, 0xc0008907e0}, 0xc0005fe370, 0xc00094f630)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:57 +0x4aa
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc00073c000, {0x17782f8?, 0xc0008906f0?}, 0xc0005fe2d0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x38e
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0xc0002e4230, {0x17782f8?, 0xc000890420?}, 0xc0005fe2d0)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00027eaa0, {0x17782f8?, 0xc0003025d0?}, 0xc000124690)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x155a8a0, 0xc00027eaa0}, {0x17782f8, 0xc0003025d0}, 0xc000928380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00054c800, {0x17782f8, 0xc000302540}, {0x1782480, 0xc00027ca80}, 0xc000148a20, 0xc000699ef0, 0x1f818b8, 0x0)
        google.golang.org/grpc@v1.64.1/server.go:1379 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc00054c800, {0x1782480, 0xc00027ca80}, 0xc000148a20)
        google.golang.org/grpc@v1.64.1/server.go:1790 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.64.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 14
        google.golang.org/grpc@v1.64.1/server.go:1040 +0x125

Error: The terraform-provider-octopusdeploy_v0.39.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
````

**Environment and versions:**
- OS: Windows
- Octopus Server Version: Cloud
- Terraform Version: 

```
Terraform v1.8.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.103.1
+ provider registry.terraform.io/hashicorp/random v3.6.1
+ provider registry.terraform.io/octopusdeploylabs/octopusdeploy v0.39.0

Your version of Terraform is out of date! The latest version
is 1.10.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### PR DESCRIPTION
**Pull request by mjhilton**
The Template and DonorPackage on a Project Versioning Strategy are mutually exclusive options, but this isn't reflected in the schema or our internal translation logic between TF State and API Resources.

Our mapping logic between the TF State and the API Resource didn't account for this, which causes #855 - the provider works fine if the `donor_package` approach is used, but crashes if the `template` approach is used. 

I took the opportunity to also fix up the schema, validation, docs and examples to better represent the actual valid inputs from the Octopus Server perspective:

* Changed `donor_package` in the schema from Required to Optional
* Changed child attributes of `donor_package` to be required, when `donor_package` is present
* Added new validation that checks that:
  1. Both `donor_package` and `donor_package_step_id` must be present together
  2. Only one of `template` or `donor_package` can be used 
* Updated documentation with clearer examples of the two approaches

Fixes #855

*Note*: These updates are _not_ a breaking change, because even though it was previously possible from a TF perspective to specify both `donor_package` and `template` in a config, Octopus Server API has a server-side check that prevents such a strategy from being applied, and fails the `terraform apply`, so it's not possible for any customers to have a config that will break with this change. If that server-side check hadn't existed, we would have had to mark this as breaking due to the stricter requirements on the mutual-exclusivity.

### CODE REVIEW

**Comment by mjhilton** [comment]
[sc-102624]

File: octopusdeploy_framework/resource_project_versioning_strategy.go [hunk 1]
```diff
@@ -164,27 +169,32 @@ func (r *projectVersioningStrategyResource) Delete(ctx context.Context, req reso
...
 	}
-
-	return &projects.VersioningStrategy{
-		Template:           state.Template.ValueString(),
-		DonorPackageStepID: donorPackageStepID,
-		DonorPackage: &packages.DeploymentActionPackage{
+	if !(state.DonorPackageStepID.IsNull()) {
+		projectVersioningStrategy.DonorPackageStepID = state.DonorPackageStepID.ValueStringPointer()
+	}
+	if !(state.DonorPackage == nil) {
```
Comment (domenicsim1) [inline octopusdeploy_framework/resource_project_versioning_strategy.go:179]: I am guessing you do this to match the above line over != nil?

File: octopusdeploy_framework/schemas/project_versioning_strategy.go [hunk 2]
```diff
@@ -35,34 +38,51 @@ func (p ProjectVersioningStrategySchema) GetResourceSchema() resourceSchema.Sche
...
+		resourcevalidator.Conflicting(
+			path.MatchRoot("template"),
+			path.MatchRoot("donor_package"),
+		),
+		resourcevalidator.Conflicting(
+			path.MatchRoot("template"),
+			path.MatchRoot("donor_package_step_id"),
+		),
+	}
+}
```
Comment (domenicsim1) [inline octopusdeploy_framework/schemas/project_versioning_strategy.go:73]: 🆒

**Review by domenicsim1 — APPROVED** [review]

File: octopusdeploy_framework/resource_project_versioning_strategy.go (hunk 1 above)
Comment (mjhilton) [reply octopusdeploy_framework/resource_project_versioning_strategy.go:179]: Yeah, consistency of... polarity?... of the check, so that it's easy to scan down and understand. I would've preferred an `IsNull()` method, but it doesn't exist on the `DonorPackage` struct versus the String above.
