### PR TITLE
Fixed handling of space manager teams

### LINKED ISSUE #306: Plan/apply of a Space resource results in an error
**Describe the bug**
Initial apply of a Space via the provider succeeds. A subsequent plan will show there there is now a `teams-spacemanagers-` team that has been added by Octopus, which isn't in the config. The plan will then presume that team needs to be removed and any attempt to run apply will result in an Octopus error including `Space Managers team can't be removed from the list of space managers.`.

**Steps to reproduce**
1. Create a config file with a space defined
2. Run `terraform init` `terraform apply`
3. Run `terraform plan` and see that there's now a space managers team that is showing as going to be removed.
4. Run `terraform apply` and it will fail

**Expected behavior**
The config is valid, this should result in no changes and therefore no errors.

**Logs and other supporting information**
See screenshot.

**Screenshots**
image

**Environment and versions:**
- OS: All
- Octopus Server Version: All
- Terraform Version: 1.1.3
- Octopus Terraform Provider Version: 0.7.63

### PR DESCRIPTION
**Pull request by slewis74**
This PR updates the Space schema for Terraform to hide the special Space Managers team from the state file. This team should be an Octopus internal concern, but while it's being returned from the API the easiest option we have for now is to remove it on read and add it back in on updates.

Fixes #306

### CODE REVIEW

**Review by domenicsim1 — APPROVED** [review]
We should make sure our naming convention is consistent. Currently I see sometimes use ‘myId’ and other times ‘myID’. I recommend capitalising ID in all cases as it seems to be more common with what is standard to Go.

Otherwise LGTM! 👍🏻

**Comment by slewis74** [comment]
You meaning `spaceManagersTeamIdPrefix` might be better as `spaceManagersTeamIDPrefix`?

**Comment by domenicsim1** [comment]
> You meaning `spaceManagersTeamIdPrefix` might be better as `spaceManagersTeamIDPrefix`?

Yes,` spaceManagersTeamIdPrefix` might be better as `spaceManagersTeamIDPrefix`.
Same for `teamIds` might be batter as `teamIDs`.
As you can see:
```
func addSpaceManagers(spaceID string, teamIds []string) []string {
```
Looks inconstant having `spaceID` with id capital and teamIds without.

File: octopusdeploy/schema_space.go [hunk 1]
```diff
@@ -116,11 +130,24 @@ func setSpace(ctx context.Context, d *schema.ResourceData, space *octopusdeploy.
...
+	if err := d.Set("space_managers_teams", removeSpaceManagers(space.SpaceManagersTeams)); err != nil {
 		return fmt.Errorf("error setting space_managers_teams: %s", err)
 	}
 
 	d.Set("is_task_queue_stopped", space.TaskQueueStopped)
 
 	return nil
 }
+
+func removeSpaceManagers(teamIds []string) []string {
```
Comment (domenicsim1) [inline octopusdeploy/schema_space.go:142]: Missed this one

**Review by domenicsim1 — CHANGES_REQUESTED** [review]

**Review by domenicsim1 — APPROVED** [review]

**Review by domenicsim1 — APPROVED** [review]
