### PR TITLE
fixes #536; Implement filtering a worker pool by name

### LINKED ISSUE #536: Worker pool data source ignores the name field
**Describe the bug**
The worker pool data source can query the worker pool by its name, but this field is completely ignored.

**Steps to reproduce**
Query some worker pool and output it, with the following blocks:
```hcl
data "octopusdeploy_worker_pools" "my_worker_pool" {
  name = "my_worker_pool"
}

output "worker_pool" {
  value = data.octopusdeploy_worker_pools.my_worker_pool.worker_pools
}
```
**Expected behavior**
I expect the output to contain a single worker pool with the queried name.

**Logs and other supporting information**
Instead of the queried pool, it will receive a list of workers that don't necessarily have the expected name.

**Screenshots**
Irrelevant.

**Environment and versions:**
- OS: Doesn't matter.
- Octopus Server Version: v2023.3 (Build 10333).
- Terraform Version: v1.5.2
- Octopus Terraform Provider Version: v0.12.5

**Additional context**
To my understanding, it seems that the bug is caused because the `Name` parameter of the `WorkerPoolsQuery` struct is completely ignored [here](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/c587e190f978a41c81811e3993dc86c18ada1e51/octopusdeploy/data_source_worker_pools.go#L21).

### PR DESCRIPTION
**Pull request by itaispiegel**
Related issues:
- https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/536

### CODE REVIEW

**Review by Dgotlieb — APPROVED** [review]

**Comment by Dgotlieb** [comment]
This bugfix will be a huge help for me as well, can you please assist?
@benPearce1 @tleed5 @zentron

File: octopusdeploy/data_source_worker_pools.go [hunk 1]
```diff
@@ -39,7 +40,10 @@ func dataSourceWorkerPoolsRead(ctx context.Context, d *schema.ResourceData, m in
 			return diag.FromErr(err)
 		}
 
-		flattenedWorkerPools = append(flattenedWorkerPools, flattenWorkerPool(workerPoolResource))
+		// Octopus currently doesn't support filtering by name, so we have to do it ourselves
+		if name != "" && workerPoolResource.Name == name {
+			flattenedWorkerPools = append(flattenedWorkerPools, flattenWorkerPool(workerPoolResource))
+		}
```
Comment (mjhilton) [inline octopusdeploy/data_source_worker_pools.go:46]: I think this will break the behaviour for when people want to use `partial_name` as the filter - with no `name` value, the datasource will always return empty results.

What if we did this instead?

```suggestion
		// There is no name filter on the WorkerPools endpoint in the Octopus API, so filter in-memory if the name field is specified
		if name != "" && workerPoolResource.Name != name { continue } 
		
		flattenedWorkerPools = append(flattenedWorkerPools, flattenWorkerPool(workerPoolResource))
```

**Review by mjhilton — CHANGES_REQUESTED** [review]
I think the proposed change needs a small tweak before we can merge it

File: octopusdeploy/data_source_worker_pools.go (hunk 1 above)
Comment (itaispiegel) [reply octopusdeploy/data_source_worker_pools.go]: You're absolutely right! Fixed this 😄

Comment (mjhilton) [reply octopusdeploy/data_source_worker_pools.go]: There are some quirks of the current shape of our build/test pipeline that mean we currently need to merge to a branch within the main repo first, so we'll do that and update here when it gets released.
